Repository appknox/irene, pull requests merged in 2018-10, with the labels that each got.

#681 Handle connectivity issues
  app/components/home-page.js
  app/components/system-status/component.js
  app/components/system-status/styles.scss
  app/components/system-status/template.emblem
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/router.js
  app/routes/status.js
  app/styles/app.sass
  app/templates/components/home-page.emblem
  app/templates/status.emblem
  config/environment.js
  ember-cli-build.js
  package.json
  tests/integration/components/system-status/component-test.js
  tests/unit/routes/status-test.js
Labels: review

#695 Switch hudson api to api
  app/adapters/security/analysis.js
  app/adapters/security/attachment.js
  app/adapters/security/file.js
  app/adapters/security/project.js
  app/adapters/security/vulnerability.js
  app/components/download-app.js
  app/components/edit-analysis-details.js
  app/components/file-actions.js
  app/components/file-details.js
  app/components/file-search-overview.js
  app/components/home-page.js
  app/components/purge-api-analysis.js
Labels: in progress

#694 Fix overflowing security dashboard ui
  app/templates/components/file-actions.emblem
Labels: review

#693 Implement project search for security dashboard
  app/components/project-search-list.js
  app/templates/components/project-search-list.emblem
Labels: review

#688 Add analytics feature request & update account ID, user ID
  app/components/add-team-member.js
  app/components/create-team.js
  app/components/invite-member.js
  app/components/organization-details.js
  app/routes/authenticated.js
  config/environment.js
Labels: in progress

#696 Remove network status
  app/components/home-page.js
  app/templates/components/home-page.emblem
Labels: review

#697 Team list on project settings page
  app/adapters/project-team.js
  app/components/add-project-team/component.js
  app/components/add-project-team/template.emblem
  app/components/project-team-list/component.js
  app/components/project-team-list/template.emblem
  app/components/project-team-overview/component.js
  app/components/project-team-overview/template.emblem
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/models/project-team.js
  app/serializers/project-team.js
  app/services/realtime.js
  app/styles/app.sass
  app/templates/components/project-settings.emblem
  config/environment.js
  tests/integration/components/add-project-team/component-test.js
  tests/integration/components/project-team-list/component-test.js
  tests/integration/components/project-team-overview/component-test.js
  tests/unit/adapters/project-team-test.js
  tests/unit/models/project-team-test.js
  tests/unit/serializers/project-team-test.js
Labels: in progress

#699 Project collaborators
  app/adapters/organization-project.js
  app/adapters/project-collaborator.js
  app/components/add-project-collaborator/component.js
  app/components/add-project-collaborator/template.emblem
  app/components/project-collaborator-list/component.js
  app/components/project-collaborator-list/styles.scss
  app/components/project-collaborator-list/template.emblem
  app/components/project-collaborator-overview/component.js
  app/components/project-collaborator-overview/template.emblem
  app/components/project-team-list/styles.scss
  app/components/project-team-list/template.emblem
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/models/organization-project.js
  app/models/project-collaborator.js
  app/serializers/project-collaborator.js
  app/services/realtime.js
  app/styles/app.sass
  app/templates/components/project-settings.emblem
  config/environment.js
  tests/integration/components/add-project-collaborator/component-test.js
  tests/integration/components/project-collaborator-list/component-test.js
  tests/integration/components/project-collaborator-overview/component-test.js
  tests/unit/adapters/project-collaborator-test.js
Labels: in progress

#703 Fixed add-sso-members textarea placeholder issue
  app/components/add-sso-members/template.emblem
Labels: in progress

#698 Implement toggling api scan in security dashboard
  app/components/file-actions.js
  app/enums.js
  app/models/security/file.js
  app/styles/app.sass
  app/templates/components/file-actions.emblem
  config/environment.js
Labels: PR: Backend Dependencies, review

#706 Auto staging deployment
  .circleci/config.yml
  config/deploy.js
  package.json
Labels: in progress

#702 Added download excel report in security dashboard
  app/components/file-actions.js
  app/styles/app.sass
  app/templates/components/file-actions.emblem
Labels: in progress

#709 Fixes s3 storage status
  app/components/system-status/component.js
  app/components/system-status/template.emblem
  app/locales/en/translations.js
  app/locales/ja/translations.js
Labels: in progress
