Repository appknox/irene, pull requests merged in 2018-06, with the labels that each got.

#631 remove opbeat and bithound
  .circleci/config.yml
  README.md
Labels: in progress

#632 Use payload id for ids
  app/serializers/api-scan-options.js
  app/serializers/device-preference.js
  app/serializers/report-preference.js
  app/serializers/unknown-analysis-status.js
Labels: review

#634 Fix edit analysis
  app/adapters/report-preference.js
  app/components/analysis-details.js
  app/components/file-details.js
  app/components/report-preferences.js
  app/components/vulnerability-details.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/models/analysis.js
  app/models/project.js
  app/models/report-preference.js
  app/models/vulnerability-preference.js
  app/serializers/report-preference.js
  app/serializers/vulnerability-preference.js
  app/styles/app.sass
  app/templates/components/analysis-details.emblem
  app/templates/components/file-details.emblem
  app/templates/components/project-settings.emblem
  app/templates/components/report-preferences.emblem
  app/templates/components/vulnerability-details.emblem
  app/templates/components/vulnerability-list.emblem
  tests/integration/components/analysis-details-test.js
  tests/integration/components/report-preferences-test.js
  tests/integration/components/vulnerability-details-test.js
  tests/unit/models/analysis-test.js
  tests/unit/models/report-preference-test.js
Labels: review

#635 UI Enhancements
  app/components/analysis-details.js
  app/components/risk-tag.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/models/analysis.js
  app/models/vulnerability.js
  app/styles/app.sass
  app/templates/components/analysis-details.emblem
  app/templates/components/compare-files.emblem
  app/templates/components/compare-summary.emblem
  app/templates/components/risk-tag.emblem
  tests/integration/components/analysis-details-test.js
  tests/integration/components/risk-tag-test.js
  tests/unit/models/vulnerability-test.js
Labels: review

#638 Fixes analysis risk count to calculate based on computedRisk
  app/models/file.js
Labels: in progress

#643 Upgrades ak-ubuntu to 2.0.0
  Dockerfile
Labels: in progress

#641 Support for Untested & Passed Values in risks
  app/helpers/risk-text.js
  app/models/vulnerability-preference.js
  app/styles/app.sass
Labels: review

#644 UI enhancements
  app/authenticators/irene.js
  app/components/analysis-settings.js
  app/components/api-filter.js
  app/components/attachment-detail.js
  app/components/auth-mfa.js
  app/components/choose-list.js
  app/components/collaboration-component.js
  app/components/collaboration-details.js
  app/components/copy-password.js
  app/components/create-team.js
  app/components/dynamic-scan.js
  app/components/file-header.js
  app/components/github-account.js
  app/components/github-project.js
  app/components/invitation-accept.js
  app/components/invoice-overview.js
  app/components/jira-account.js
  app/components/jira-project.js
  app/components/login-component.js
  app/components/namespace-component.js
  app/components/namespace-modal.js
  app/components/password-change.js
  app/components/password-recover.js
  app/components/password-reset.js
  app/components/password-setup.js
  app/components/personaltoken-detail.js
  app/components/personaltoken-list.js
  app/components/pricing-list.js
  app/components/project-preferences.js
  app/components/select-language.js
  app/components/subscription-component.js
  app/components/team-details.js
  app/components/team-member.js
  app/components/team-overview.js
  app/components/upload-app.js
  app/components/vnc-viewer.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/mixins/paginate.js
  app/routes/authenticated.js
  app/routes/authenticated/payment-success.js
  app/styles/app.sass
  app/templates/components/collaboration-component.emblem
  app/templates/components/compare-files.emblem
  app/templates/components/copy-password.emblem
  app/templates/components/dynamic-scan.emblem
  app/templates/components/file-header.emblem
  app/templates/components/github-project.emblem
  app/templates/components/jira-project.emblem
  app/templates/components/project-preferences.emblem
  app/templates/components/vnc-viewer.emblem
  app/utils/uploader.js
  tests/integration/components/collaboration-component-test.js
  tests/integration/components/copy-password-test.js
  tests/integration/components/file-header-test.js
Labels: in progress

#646 UI enhancements
  app/components/namespace-component.js
  app/components/personaltoken-list.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/styles/app.sass
  app/templates/components/analysis-details.emblem
  app/templates/components/choose-list.emblem
  app/templates/components/file-list.emblem
  app/templates/components/namespace-component.emblem
  app/templates/components/personaltoken-detail.emblem
  app/templates/components/personaltoken-list.emblem
  app/templates/components/project-list.emblem
  tests/integration/components/namespace-component-test.js
Labels: review

#647 New devicefarm
  app/adapters/available-device.js
  app/components/dynamic-scan.js
  app/components/file-header.js
  app/components/project-preferences.js
  app/models/available-device.js
  app/serializers/available-device.js
  app/templates/components/project-preferences.emblem
  config/environment.js
  tests/unit/models/available-device-test.js
Labels: in progress

#648 Hot fix
  mirage/config.js
  tests/integration/components/dynamic-scan-test.js
Labels: review, type:bug

#650 Activate whitelabel only if whitelabel enabled is true
  config/environment.js
Labels: in progress

#652 Fix risk tag
  app/components/compare-summary.js
  app/models/analysis.js
  app/templates/components/risk-tag.emblem
Labels: in progress, type:bug

#653 Disable enterprise registration
  app/components/login-component.js
  app/models/user.js
  app/router.js
  app/templates/components/login-component.emblem
Labels: in progress
