Repository appknox/irene, pull requests merged in 2018-02, with the labels that each got.

#579 More UI Enhancement
  app/authenticators/irene.coffee
  app/components/analysis-settings.coffee
  app/components/api-filter.coffee
  app/components/auth-mfa.coffee
  app/components/collaboration-details.coffee
  app/components/github-account.coffee
  app/components/github-project.coffee
  app/components/jira-account.coffee
  app/components/login-component.coffee
  app/components/password-change.coffee
  app/components/password-recover.coffee
  app/components/password-reset.coffee
  app/components/password-setup.coffee
  app/components/personaltoken-detail.coffee
  app/components/project-preferences.coffee
  app/components/select-language.coffee
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/styles/app.sass
  app/templates/authenticated.emblem
  app/templates/components/analysis-settings.emblem
  app/templates/components/api-filter.emblem
  app/templates/components/auth-mfa.emblem
  app/templates/components/collaboration-component.emblem
  app/templates/components/collaboration-details.emblem
  app/templates/components/confirm-box.emblem
  app/templates/components/create-team.emblem
  app/templates/components/file-header.emblem
  app/templates/components/github-account.emblem
  app/templates/components/github-project.emblem
  app/templates/components/jira-account.emblem
  app/templates/components/login-component.emblem
  app/templates/components/namespace-component.emblem
  app/templates/components/password-change.emblem
  app/templates/components/password-recover.emblem
  app/templates/components/password-reset.emblem
  app/templates/components/password-setup.emblem
  app/templates/components/personaltoken-detail.emblem
  app/templates/components/personaltoken-list.emblem
  app/templates/components/project-preferences.emblem
  app/templates/components/prompt-box.emblem
  app/templates/components/select-language.emblem
  app/templates/components/team-details.emblem
  config/environment.js
  mirage/config.js
  tests/integration/components/password-reset-test.coffee
  tests/integration/components/password-setup-test.coffee
Labels: type:enhancement

#580 Adds whitelabel theme
  app/router.coffee
  app/styles/app.sass
  app/templates/components/img-logo.emblem
  config/environment.js
Labels: in progress

#584 Other changes for new UI
  .gitignore
  app/components/file-header.coffee
  app/components/invoice-overview.coffee
  app/components/jira-account.coffee
  app/components/jira-project.coffee
  app/components/upload-app.coffee
  app/components/vnc-viewer.coffee
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/styles/app.sass
  app/templates/components/file-header.emblem
  app/templates/components/invoice-overview.emblem
  app/templates/components/password-reset.emblem
  app/templates/components/vnc-viewer.emblem
  app/utils/uploader.coffee
  config/deploy.js
Labels: in progress, type:enhancement

#585 Minor ui fixes
  app/styles/app.sass
  app/templates/authenticated/file.emblem
  app/templates/components/file-details.emblem
Labels: in progress, type:enhancement
