Repository appknox/irene, pull requests merged in 2018-05, with the labels that each got.

#616 Adds accept terms checkbox in register form
  app/components/register-component.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/styles/app.sass
  app/templates/components/register-component.emblem
  app/validations/register.js
  app/validations/validators/value-equality.js
Labels: in progress

#615 Update Register Page
  app/components/register-component.js
  app/styles/app.sass
  app/templates/components/login-component.emblem
  app/templates/components/register-component.emblem
  app/validations/register.js
  config/environment.js
  package.json
Labels: PR: Backend Dependencies, review

#622 UI enhancements
  app/components/dynamic-scan.js
  app/components/file-header.js
  app/components/github-project.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/styles/app.sass
  app/templates/components/api-filter.emblem
  app/templates/components/dynamic-scan.emblem
  app/templates/components/file-details.emblem
  app/templates/components/file-header.emblem
  app/templates/components/project-preferences.emblem
  app/templates/components/vnc-viewer.emblem
  tests/integration/components/dynamic-scan-test.js
  tests/integration/components/file-details-test.js
  tests/integration/components/file-header-test.js
  tests/integration/components/project-preferences-test.js
  tests/integration/components/vnc-viewer-test.js
Labels: in progress

#617 Implement PCI-DSS compliance
  app/components/pcidss-details.js
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/models/analysis.js
  app/models/pcidss.js
  app/styles/app.sass
  app/templates/components/analysis-details.emblem
  app/templates/components/pcidss-details.emblem
  tests/integration/components/pcidss-details-test.js
  tests/unit/models/analysis-test.js
Labels: PR: Backend Dependencies, in progress

#623 Minor ui fix
  app/styles/app.sass
Labels: review

#624 Show exit full screen when user stops the scan in fullscreen mode
  app/components/vnc-viewer.js
  app/templates/components/vnc-viewer.emblem
Labels: review

#625 Text refactor
  app/locales/en/translations.js
  app/locales/ja/translations.js
  app/templates/components/analysis-settings.emblem
  app/templates/components/file-header.emblem
  app/templates/components/file-overview.emblem
Labels: PR: Backend Dependencies, review

#627 Disable button after dynamic/api scan is initiated
  app/components/dynamic-scan.js
  app/templates/components/dynamic-scan.emblem
Labels: review

#628 Adds polling for dynamic status
  app/components/dynamic-scan.js
  app/services/poll.js
  tests/integration/components/dynamic-scan-test.js
Labels: in progress
