Repository appknox/irene, pull requests merged in 2019-02, with the labels that each got.

#723 Enable edit analysis
  app/templates/components/analysis-details.emblem
  app/templates/components/project-settings.emblem
Labels: review

#719 Replace available-devices with nested project api
  app/adapters/project-available-device.js
  app/components/project-preferences.js
  app/models/project-available-device.js
  app/serializers/project-available-device.js
  app/templates/components/project-settings.emblem
  tests/integration/components/project-preferences-test.js
Labels: in progress

#727 Add missing translations
  app/locales/ja/translations.js
Labels: review

#728 Disable edit analysis
  app/templates/components/analysis-details.emblem
  app/templates/components/project-settings.emblem
Labels: review

#729 Fix Device Preference API call
  app/templates/components/dynamic-scan.emblem
Labels: review, type:bug

#715 Use api_scan_status and update the ui
  app/models/file.js
  tests/unit/models/file-test.js
Labels: review

#722 Remove Intercom & Add Crisp
  app/app.js
  app/components/home-page.js
  app/models/user.js
  app/routes/authenticated.js
  app/templates/components/home-page.emblem
  app/utils/chat.js
  app/utils/install-crisp.js
  app/utils/install-intercom.js
  config/environment.js
  tests/unit/utils/chat-test.js
  tests/unit/utils/install-crisp-test.js
Labels: PR: Backend Dependencies, review

#731 Disable register page and move the link to new registration page
  app/components/login-component.js
  app/initializers/irene.js
  app/router.js
  app/templates/components/login-component.emblem
  config/deploy.js
  config/environment.js
Labels: in progress

#730 Set user company to crisp
  app/routes/authenticated.js
  app/utils/chat.js
Labels: PR: Backend Dependencies, review

#732 Upgraded ak-ubuntu 2.0.0 → 2.0.2
  Dockerfile
Labels: in progress
